CREATE TABLE clientes (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    telefono VARCHAR2(20),
    direccion VARCHAR2(200)
);

CREATE TABLE productos (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    precio NUMBER(10,2),
    stock NUMBER
);

CREATE TABLE ventas (
    id_venta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente NUMBER REFERENCES clientes(id_cliente),
    fecha DATE DEFAULT SYSDATE,
    total NUMBER(10,2)
);

CREATE TABLE detalle_ventas (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta NUMBER REFERENCES ventas(id_venta),
    id_producto NUMBER REFERENCES productos(id_producto),
    cantidad NUMBER,
    subtotal NUMBER(10,2)
);
